title: RHEL Performance Guide
description: A complete guide to RHEL performance tuning and monitoring

remote_theme: rundocs/jekyll-rtd-theme
"test"
defaults:
  - scope:
      path: "README.md"
    values:
      permalink: "index.html"
